// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunningJac.IDP.DbContexts;

namespace RunningJac.IDP.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20231121224002_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RunningJac.IDP.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "dab7b0a2-54a9-4d32-94e4-9a7f8d26ecdf",
                            IsActive = true,
                            Password = "#&okodf1t90ejyuhDF",
                            Subject = "e7cd9d8e-38e9-4b6a-a7b0-8c17b4cf10d1",
                            Username = "Odira"
                        },
                        new
                        {
                            Id = "8e48e3d7-11f9-4ecb-9cd5-9514fe4a09b6",
                            IsActive = true,
                            Password = "#%6wr90ujkjwmklOLw",
                            Subject = "f9f95db5-82b3-4aa6-84b7-35c586be8042",
                            Username = "Somto"
                        });
                });

            modelBuilder.Entity("RunningJac.IDP.Entities.UserClaim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");

                    b.HasData(
                        new
                        {
                            Id = "b37d1681-6d0c-4cb5-8d98-0a446f9765e1",
                            Type = "given_name",
                            UserId = "dab7b0a2-54a9-4d32-94e4-9a7f8d26ecdf",
                            Value = "Odira"
                        },
                        new
                        {
                            Id = "c03d7464-2cf2-4f3c-81b0-3f7da739e383",
                            Type = "family_name",
                            UserId = "dab7b0a2-54a9-4d32-94e4-9a7f8d26ecdf",
                            Value = "Ike"
                        },
                        new
                        {
                            Id = "a0f1b4f0-3809-4c4f-a3f0-17787d2c013c",
                            Type = "role",
                            UserId = "dab7b0a2-54a9-4d32-94e4-9a7f8d26ecdf",
                            Value = "admin"
                        },
                        new
                        {
                            Id = "9a0bfa87-df71-4b07-a3c3-9ec61b7ec2a5",
                            Type = "country",
                            UserId = "dab7b0a2-54a9-4d32-94e4-9a7f8d26ecdf",
                            Value = "ng"
                        },
                        new
                        {
                            Id = "c8c66c9f-b309-417b-9b4b-785c02f6f3d8",
                            Type = "given_name",
                            UserId = "8e48e3d7-11f9-4ecb-9cd5-9514fe4a09b6",
                            Value = "Somto"
                        },
                        new
                        {
                            Id = "4bdfec12-318a-4df6-a1a7-94272905724e",
                            Type = "family_name",
                            UserId = "8e48e3d7-11f9-4ecb-9cd5-9514fe4a09b6",
                            Value = "Ikewelugo"
                        },
                        new
                        {
                            Id = "4ef412d3-8e06-4ab3-b2a1-7e2246824cd9",
                            Type = "role",
                            UserId = "8e48e3d7-11f9-4ecb-9cd5-9514fe4a09b6",
                            Value = "regular_user"
                        },
                        new
                        {
                            Id = "946bc5b4-0a3a-4f47-946d-94a149e24256",
                            Type = "country",
                            UserId = "8e48e3d7-11f9-4ecb-9cd5-9514fe4a09b6",
                            Value = "ng"
                        });
                });

            modelBuilder.Entity("RunningJac.IDP.Entities.UserClaim", b =>
                {
                    b.HasOne("RunningJac.IDP.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RunningJac.IDP.Entities.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
